players:
  Notch: 1.2
finished:
  Notch: 10910.3

commandsToExecute:
  - 'say %player% has finished the speedrun. %player% is awesome!'
commandsToExecuteOnReset:
  - 'say %player% timer has been reset by a mysterious creature!'

mainWorld: world
schematicWorld: flatworld