players:
  Notch: 1.2
finished:
  Notch: 10910.3

commandsToExecute:
  - 'say %player% has finished the speedrun. %player% is awesome!'
commandsToExecuteOnReset:
  - 'say %player% timer has been reset by a mysterious creature!'

mainWorld: world
schematicWorld: flatworld

# Button is automatically added in the 9th slot
# Format: MATERIAL:AMOUNT
portal_items:
  - 'BUCKET:1'
  - 'WATER_BUCKET:1'
  - 'FLINT_AND_STEEL:1'
  - 'OAK_LEAVES:32'

breakable_block_types:
  - 'OAK_LEAVES'
